### PR TITLE
Add wandb integration

### PR DESCRIPTION
**Pull request by tcapelle**
Hey, great work!

I started playing with your code today and refactored some bits...
- EMA is not being sampled, do you want to sample from that model to and compare?
- Have you tried mixed precision training? I can add that if you want.

Sincerely,
Thomas

### CODE REVIEW

**Comment by cloneofsimo** [comment]
Hey @tcapelle! Thank you for the PR.
I love what you did there, integrating wandb. but I'm not sure if this is what should be as the main example file. (just because it creates bit more side code that's not crucial for the implementation)

If you don't mind, uploading different file with wandb implementations as example folder would be helpful to the newcomers who just want to see the implementation.

Thanks!

**Comment by tcapelle** [comment]
Hey, I am having fun with the codebase 😆 .

I am very convinced that you need experiment tracking to train these types of models, as you want to be able to sample images to see the how model evolved over time. I can put a parallel file if you want.

I have been running some experiments here: https://wandb.ai/capecape/consistency-model

**Comment by cloneofsimo** [comment]
Thanks for the experiments! Link you've shared is private btw, (if that's what you didn't intend)

**Comment by tcapelle** [comment]
It was missing a final `l`.
I will make a new PR and close this one.

**Pull request closed without merging**
